CREATE TABLE IF NOT EXISTS MEMBER (
    MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS COFFEE(
    COFFEE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    KOR_NAME VARCHAR(100) NOT NULL,
    ENG_NAME VARCHAR(100) NOT NULL,
    PRICE INT NOT NULL,
    COFFEE_CODE CHAR(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    ORDER_STATUS VARCHAR(20) NOT NULL,
    CREATED_AT datetime NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_COFFEE(
    ORDER_COFFEE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    COFFEE_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (COFFEE_ID) REFERENCES COFFEE(COFFEE_ID)
);